"""
infra/setup_dms.py
──────────────────
Manages all AWS DMS resources:
  - Replication instance (provision + wait)
  - Source endpoint  (PostgreSQL, SSL, test_decoding plugin)
  - Target endpoint  (S3, Parquet + GZIP)
  - Endpoint connection tests
  - Replication task (full-load-and-cdc)
  - Task reload (full-load from scratch on every run)

Requires DYNAMIC_DB_PASSWORD and DYNAMIC_DB_ENDPOINT to be set
before calling create_source_endpoint(). These are passed in from
setup_pipeline.py after setup_rds.py runs.
"""

import boto3
import json
import time

with open("config/infra_config.json") as f:
    config = json.load(f)

region    = config["aws"]["region"]
ROLE_NAME = config["iam"]["role_name"]

dms = boto3.client("dms", region_name=region)
iam = boto3.client("iam")


def log(msg):
    print(f"[{time.strftime('%H:%M:%S')}] {msg}")


# ─────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────

def _safe_describe_replication_instances(instance_id):
    try:
        return dms.describe_replication_instances(
            Filters=[{"Name": "replication-instance-id", "Values": [instance_id]}]
        )["ReplicationInstances"]
    except dms.exceptions.ResourceNotFoundFault:
        return []


def _safe_describe_endpoints(endpoint_id):
    try:
        return dms.describe_endpoints(
            Filters=[{"Name": "endpoint-id", "Values": [endpoint_id]}]
        )["Endpoints"]
    except dms.exceptions.ResourceNotFoundFault:
        return []


def _safe_describe_tasks(task_id):
    try:
        return dms.describe_replication_tasks(
            Filters=[{"Name": "replication-task-id", "Values": [task_id]}]
        )["ReplicationTasks"]
    except dms.exceptions.ResourceNotFoundFault:
        return []


# ─────────────────────────────────────────────
# STEP 4 — Replication instance
# ─────────────────────────────────────────────

def create_replication_instance():
    log("STEP 4 — Setting up DMS replication instance")
    cfg = config["dms"]
    net = config["network"]

    existing = _safe_describe_replication_instances(cfg["replication_instance_id"])
    if existing:
        log("  Replication instance exists — skipping")
        return

    log("  Creating replication instance...")
    dms.create_replication_instance(
        ReplicationInstanceIdentifier    = cfg["replication_instance_id"],
        ReplicationInstanceClass         = cfg["instance_class"],
        AllocatedStorage                 = cfg["allocated_storage"],
        PubliclyAccessible               = cfg["public_access"],
        MultiAZ                          = cfg["multi_az"],
        ReplicationSubnetGroupIdentifier = net["subnet_group"],
        VpcSecurityGroupIds              = [net["security_group_id"]]
    )

    log("  Waiting for instance to become available (~5 mins)...")
    while True:
        instances = _safe_describe_replication_instances(cfg["replication_instance_id"])
        if instances and instances[0]["ReplicationInstanceStatus"] == "available":
            break
        time.sleep(15)

    log("  Replication instance ready")


# ─────────────────────────────────────────────
# STEP 5 — Source endpoint (PostgreSQL)
# ─────────────────────────────────────────────

def create_source_endpoint(db_password: str, db_endpoint: str):
    """
    Args:
        db_password: retrieved/generated by setup_rds.manage_db_credentials()
        db_endpoint: the RDS hostname from setup_rds.create_rds_database()
    """
    log("STEP 5 — Setting up source endpoint (PostgreSQL)")
    cfg = config["rds"]
    ep  = config["endpoints"]

    if _safe_describe_endpoints(ep["source_id"]):
        log("  Source endpoint exists — skipping")
        return

    dms.create_endpoint(
        EndpointIdentifier        = ep["source_id"],
        EndpointType              = "source",
        EngineName                = "postgres",
        Username                  = cfg["username"],
        Password                  = db_password,
        ServerName                = db_endpoint,
        Port                      = 5432,
        DatabaseName              = cfg["database"],
        SslMode                   = "require",
        # test_decoding is the correct plugin for RDS PostgreSQL + DMS.
        # pgoutput requires manual replication slot setup which RDS restricts.
        ExtraConnectionAttributes = "pluginName=test_decoding"
    )
    log("  Source endpoint created (SSL enabled, plugin=test_decoding)")


# ─────────────────────────────────────────────
# STEP 6 — Target endpoint (S3)
# ─────────────────────────────────────────────

def create_target_endpoint():
    log("STEP 6 — Setting up target endpoint (S3)")
    s3_cfg = config["s3"]
    ep     = config["endpoints"]

    if _safe_describe_endpoints(ep["target_id"]):
        log("  Target endpoint exists — skipping")
        return

    role = iam.get_role(RoleName=ROLE_NAME)

    dms.create_endpoint(
        EndpointIdentifier = ep["target_id"],
        EndpointType       = "target",
        EngineName         = "s3",
        S3Settings         = {
            "ServiceAccessRoleArn": role["Role"]["Arn"],
            "BucketName":           s3_cfg["bucket"],
            "BucketFolder":         s3_cfg["prefix"],
            "DataFormat":           "parquet",
            "CompressionType":      "GZIP",
            "DatePartitionEnabled": s3_cfg["date_partition"],
            "CdcMinFileSize":       1,
            "CdcMaxBatchInterval":  60
        }
    )
    log("  Target endpoint created")


# ─────────────────────────────────────────────
# STEP 7 — Test endpoint connections
# ─────────────────────────────────────────────

def test_endpoints():
    log("STEP 7 — Testing endpoint connections")
    ep  = config["endpoints"]
    cfg = config["dms"]

    instance_arn = _safe_describe_replication_instances(
        cfg["replication_instance_id"]
    )[0]["ReplicationInstanceArn"]

    endpoints  = dms.describe_endpoints()["Endpoints"]
    source_arn = next(e["EndpointArn"] for e in endpoints if e["EndpointIdentifier"] == ep["source_id"])
    target_arn = next(e["EndpointArn"] for e in endpoints if e["EndpointIdentifier"] == ep["target_id"])

    for ep_arn, ep_name in [(source_arn, "source"), (target_arn, "target")]:
        log(f"  Testing {ep_name} endpoint connection...")
        try:
            dms.test_connection(ReplicationInstanceArn=instance_arn, EndpointArn=ep_arn)
        except Exception as e:
            log(f"  Test initiated: {str(e)[:80]}")

        passed = False
        for _ in range(20):
            time.sleep(10)
            conns = dms.describe_connections(
                Filters=[
                    {"Name": "replication-instance-arn", "Values": [instance_arn]},
                    {"Name": "endpoint-arn",             "Values": [ep_arn]}
                ]
            ).get("Connections", [])

            if conns:
                status = conns[0]["Status"]
                if status == "successful":
                    log(f"  {ep_name} endpoint test: PASSED")
                    passed = True
                    break
                elif status == "failed":
                    error = conns[0].get("LastFailureMessage", "Unknown error")
                    raise RuntimeError(f"Endpoint test failed: {ep_name} — {error}")

        if not passed:
            log(f"  WARNING: {ep_name} endpoint test did not complete in time — check AWS console")


# ─────────────────────────────────────────────
# STEP 8 — Replication task
# ─────────────────────────────────────────────

def create_task():
    log("STEP 8 — Setting up DMS replication task")
    cfg = config["dms"]
    eps = config["endpoints"]

    existing = _safe_describe_tasks(cfg["task_id"])
    if existing:
        log("  Task exists — skipping creation.")
        return

    endpoints    = dms.describe_endpoints()["Endpoints"]
    source_arn   = next(e["EndpointArn"] for e in endpoints if e["EndpointIdentifier"] == eps["source_id"])
    target_arn   = next(e["EndpointArn"] for e in endpoints if e["EndpointIdentifier"] == eps["target_id"])
    instance_arn = _safe_describe_replication_instances(
        cfg["replication_instance_id"]
    )[0]["ReplicationInstanceArn"]

    dms.create_replication_task(
        ReplicationTaskIdentifier = cfg["task_id"],
        SourceEndpointArn         = source_arn,
        TargetEndpointArn         = target_arn,
        ReplicationInstanceArn    = instance_arn,
        MigrationType             = "full-load-and-cdc",
        TableMappings             = json.dumps({
            "rules": [{
                "rule-type":      "selection",
                "rule-id":        "1",
                "rule-name":      "all",
                "object-locator": {"schema-name": "public", "table-name": "%"},
                "rule-action":    "include"
            }]
        })
    )

    log("  Task created. Waiting for ready state...")
    tasks = []
    while True:
        tasks = _safe_describe_tasks(cfg["task_id"])
        if tasks and tasks[0]["Status"] == "ready":
            break
        time.sleep(5)

    dms.start_replication_task(
        ReplicationTaskArn       = tasks[0]["ReplicationTaskArn"],
        StartReplicationTaskType = "start-replication"
    )
    log("  DMS task started successfully.")


# ─────────────────────────────────────────────
# STEP 9 — Reload task (full-load from scratch)
# ─────────────────────────────────────────────

def reload_dms_task():
    """
    Stops the task if running, then does a reload-target so that
    a fresh full-load is triggered on every setup run.
    """
    log("STEP 9 — Reloading DMS task (full-load from scratch)")
    cfg   = config["dms"]
    tasks = _safe_describe_tasks(cfg["task_id"])

    if not tasks:
        log("  No task found — skipping reload")
        return

    task_arn = tasks[0]["ReplicationTaskArn"]
    status   = tasks[0]["Status"]
    log(f"  Current task status: {status}")

    if status in ("running", "starting"):
        log("  Stopping task before reload...")
        dms.stop_replication_task(ReplicationTaskArn=task_arn)
        while True:
            tasks  = _safe_describe_tasks(cfg["task_id"])
            status = tasks[0]["Status"]
            if status == "stopped":
                break
            log(f"  Waiting for task to stop (current: {status})...")
            time.sleep(10)
        log("  Task stopped")

    log("  Starting reload-target (full-load from scratch)...")
    dms.start_replication_task(
        ReplicationTaskArn       = task_arn,
        StartReplicationTaskType = "reload-target"
    )

    log("  Waiting for task to begin running...")
    for _ in range(24):   # up to 4 minutes
        time.sleep(10)
        tasks  = _safe_describe_tasks(cfg["task_id"])
        status = tasks[0]["Status"]
        if status == "running":
            log("  Task is running — full-load in progress")
            log(f"  Check s3://{config['s3']['bucket']}/raw/public/ in a few minutes")
            return
        elif status == "failed":
            stop_reason = tasks[0].get("StopReason", "Unknown")
            raise RuntimeError(f"DMS task failed during reload: {stop_reason}")
        log(f"  Task status: {status} — waiting...")

    log("  WARNING: Task did not reach running state in time — check AWS DMS console")
